### PR TITLE
Add uninstall profile

### PR DESCRIPTION
**Pull request by bsuttor**
I added an uninstall profile because of this ticket https://github.com/plone/plone.app.multilingual/issues/183

cc @Gomez

### CODE REVIEW

**Comment by Gomez** [comment]
Good work!

**Comment by mauritsvanrees** [comment]
It seems I may need this.
Could we get a new release with this please? Or grant the `plone` user release rights on PyPI, then I can do it myself.
Current PyPI owners or maintainers: @bloodbare @saily @sneridagh @pysailor

**Comment by saily** [comment]
@mauritsvanrees, _plone_ user is now maintainer of `plone.multilingualbehavior` on pypi.

**Comment by mauritsvanrees** [comment]
Thank you. I have released 1.2.2.

**Pull request merged**
